# Generated by Django 4.1.2 on 2022-11-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date_time', models.DateTimeField(auto_now_add=True)),
                ('update_date_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('contact', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('salary', models.FloatField()),
                ('address', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
